package com.example.walletsim_backend.enums;
public enum ErrorCode {
    VALIDATION_ERROR,
    INSUFFICIENT_BALANCE,
    INVALID_CREDENTIALS,
    TOKEN_EXPIRED,
    TOKEN_MISSING,
    TOKEN_INVALID,
    INVALID_ADDRESS,
    QUOTE_EXPIRED,
    PIN_INCORRECT,
    EMAIL_TAKEN,
    EMAIL_NOT_VERIFIED,
    WALLET_NOT_FOUND,
    USER_NOT_FOUND,
    TRANSACTION_NOT_FOUND,
    ACCESS_DENIED,
    ACCOUNT_SUSPENDED,
    KYC_REQUIRED,
    LIMIT_EXCEEDED,
    INTERNAL_ERROR,
    RATE_LIMITED;

}
